### ISSUE TITLE
tooltips are only displaying once

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#135]

**Comment by mccxiv** [comment]
probably an angular-material bug

**Comment by mccxiv** [comment]
updated to latest release and it's still happening

**Comment by mccxiv** [comment]
can't find any info on this :(

**Comment by kumpelblase2** [comment]
Windows only issue it seems. Was able to replicate it within Windows 10 preview, but no issues with Ubuntu 14.04 and OSX 10.10.

**Comment by mccxiv** [comment]
we did it boys
