### ISSUE TITLE
Mac Version?

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#158]
What's missing from the OS X version to make it behave like a proper, polished app?

@kumpelblase2

**Comment by kumpelblase2** [comment]
Well there are two things which would prevent me from saying it is 'polished'.

1. No settings shortcut or menu bar entry. This should be existing in any OSX app that has settings, as this one does.
2. The menu bar icon is kinda weird 
![bildschirmfoto 2015-07-15 um 21 48 32](https://cloud.githubusercontent.com/assets/765835/8708272/4ae9efb6-2b3b-11e5-8a3e-3f4040a3dcca.png) You see this bar on the right? I don't know where it comes from or why it is there, but that's just irritating.
3. Nw.js quits the app when you close the main window. This is not the default osx behavior. Instead it should just close the window but let the application continue to run. I know this is not possible in nw.js but instead we could probably just hide it.

Those are the things I would have an issue with.

**Comment by mccxiv** [comment]
So how is closing the app different from the minimize behavior?

**Comment by kumpelblase2** [comment]
Minimizing the app puts it in the dock, next to all the other things, by default. Closing it normally removes the window and whenever the app regains focus, it will create a new window. For applications working with documents, this would then for example open a new document directly. This doesn't really make any sense here, so hiding the window (!= minimizing) is probably an easier way to do it.

**Comment by mccxiv** [comment]
Been working on this, stay tuned!

**Comment by mccxiv** [comment]
Ayyy we did it!
