### ISSUE TITLE
ability to hide viewer list

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#187]
Throw up a toast explaining how to re enable it

**Comment by kumpelblase2** [comment]
I would probably hide either the thumbnail or the whole sidebar, I don't think there's much gain from hiding the viewerlist individually because what would you put there once it's hidden? White space? Might as well just hide the whole sidebar.

**Comment by mccxiv** [comment]
believe it or not, I've gotten feedback from streamers that don't want to see the list because it gives them anxiety :smiley:

**Comment by kumpelblase2** [comment]
well yes, I saw that. What I'm saying is that I don't think it makes sense to allow hiding the viewerlist _alone_. For me, it would make so much more sense to just hide that sidebar as a whole. I mean, when you stream, you probably won't look at the thumbnail either, right?

**Comment by mccxiv** [comment]
Ok I see what you mean, so do only #188 instead of this?

**Comment by kumpelblase2** [comment]
yes and possibly #186, because you could also benefit from hiding it because the viewerlist could take up more space. Hiding the thumbnail makes sense because the viewerlist could take up the space, the other way around however wouldn't work.
