### ISSUE TITLE
Simplify tray functionality

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#200]
close to tray, minimize to taskbar, not customizeable.

**Comment by kumpelblase2** [comment]
> not customizeable
I would not expect the tray to be customizeable in general so you explicitly stating this made me curious if you might have something in mind?

**Comment by mccxiv** [comment]
Hello @kumpelblase2 
I was referring to this options panel, I want to replace it with a simple on/off for the tray icon. Less logic customization.
![](http://puu.sh/l3aHx/56f156c0e9.png)

**Comment by kumpelblase2** [comment]
Ah so not the tray itself, but the behavior towards the tray. Ok got it.
