### ISSUE TITLE
BTTV and FFZ emotes don't seem to well together.

### ISSUE THREAD

**Issue by Zelakto** [mccxiv/tc#225]
See [this](https://screenshots.zelakto.tv/s/ORBDsKYIU7GAg6KzHnjvWFVUd.png).

The FFZ emotes are in the middle, while the BTTV emotes are on the outside. Not sure if the same thing happens with non-gif BTTV emotes and what not.

**Comment by mccxiv** [comment]
Thanks :heart: 
I'll be taking a look .

**Comment by mccxiv** [comment]
Fixed. Should update on restart or you can force it by just opening the options menu
