### ISSUE TITLE
Spam block, chat filter.

### ISSUE THREAD

**Issue by MaximUSNG** [mccxiv/tc#237]
Hi. Great app! Is it possible to add filters to the chat as in this expansion?
https://chrome.google.com/webstore/detail/twitch-spamblock/mmelhdhaidahpljgmacnmmckdfipmddg?utm_source=chrome-app-launcher-info-dialog

**Comment by mccxiv** [comment]
I like that. I'm planning to rewrite a portion of Tc to make it easy to add filters and transformations to incoming or outgoing messages.

Once I have that system this should be simple to implement.

**Comment by mccxiv** [comment]
Ok, this is currently outside of the scope of Tc but contributions are welcome. Feel free to reopen as needed.
