### ISSUE TITLE
Being able to change game, title, etc straight from Tc.

### ISSUE THREAD

**Issue by Zelakto** [mccxiv/tc#243]

**Comment by mccxiv** [comment]
Sounds good but seems like a lot of work to make the UI for it (game auto completion).

Quick ideas for now:
- Add a link to your dashboard if you're in your own channel
- Ability to do it via /slash commands

I'm in the middle of a big refactor (ES6/7 + module bundler) so I want to finish that first

**Comment by mccxiv** [comment]
Ok, I've started work on this and some other stats features, will be tracked at #301
