### ISSUE TITLE
Blank screen when launching application

### ISSUE THREAD

**Issue by johnmadrak** [mccxiv/tc#260]
When I launch the application on my computer I get the usual loading blocks then a blank screen.

My OS is Windows 10. If there's anything else I can provide that would be helpful, please let me know.

<img width="591" alt="error" src="https://cloud.githubusercontent.com/assets/2885480/15562427/06749a68-22cd-11e6-87e4-36d3e874e2b7.png">

**Comment by mccxiv** [comment]
Thanks for the report, are you able to open the developer tools by pressing F12? If so, could you provide a screenshot of any errors in there.

**Comment by johnmadrak** [comment]
Thanks for the reply.

<img width="592" alt="error2" src="https://cloud.githubusercontent.com/assets/2885480/15562645/05c31908-22cf-11e6-874a-dee6f44d2307.png">

**Comment by mccxiv** [comment]
I've gotten other reports of this same issue, I'll do some investigating later today

**Comment by mccxiv** [comment]
All right, it's been fixed. 

You can manually download 1.3.5 or hope to get an auto-update by reopening 1.3.4 and letting it sit there for a few minutes.

Leaving this issue open for a bit so more people see it.

**Comment by johnmadrak** [comment]
That worked! Thanks for the quick fix. :+1:
