### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by johnmadrak** [mccxiv/tc#261]
After the previous issue with the blank screen was resolved I've found that I am unable to connect to chat. I've tried signing out and back in a few times, however it hasn't worked.

The chat "backlog" will load in and I'll see a Connecting message, then Disconnected, then multiple Connecting lines that will continue but it will never connect.

If I close the window and reopen it the backlog is shown again.

From the developer console:
```
[08:03pm] error: Could not connect to server. Trying to reconnect in 10 seconds..
2renderer.js:121052 [08:03pm] error: Cannot disconnect from server. Socket is not opened or connection is already closing.
renderer.js:72807 Uncaught (in promise) Cannot disconnect from server. Socket is not opened or connection is already closing.
renderer.js:72807 Uncaught (in promise) Cannot disconnect from server. Socket is not opened or connection is already closing.
```

**Comment by mccxiv** [comment]
Still happening? Seems like a generic connection issue. 

Was it working fine before?

**Comment by johnmadrak** [comment]
It works on my desktop but not on my laptop, but they're very different environments. Desktop is OS X and has had it for a while, laptop is Windows 10 with a fresh install.

**Comment by johnmadrak** [comment]
I discovered one issue was that when I changed my oauth info in the UI it wasn't actually updating. I verified this by checking the network tab after several attempts and it was always using the old information.

To work around this, I removed the files from appdata and reinstalled, entering the new key and it is now using the right oauth key but it still can't connect.

**Comment by johnmadrak** [comment]
I managed to track down the issue - it turns out my Antivirus was blocking Tc from connecting to Twitch. I haven't had this issue with other apps (even other Twitch apps) but for some reason it blocked Tc. Once I made some adjustments to it I was able to connect.

**Comment by mccxiv** [comment]
Thanks for posting your solution, which AV is this?
