### ISSUE TITLE
Request: Host Button

### ISSUE THREAD

**Issue by ghost** [mccxiv/tc#263]
Hi!

Would love to get the function to host a channel.

**Comment by mccxiv** [comment]
> I am a viewer and I want to host the channel I'm currently watching

vs

> I am the channel owner or a mod and want to host another channel here

Which do you mean?

**Comment by Punisher-biz** [comment]
I am a viewer and I want to host the channel I'm currently watching

**Comment by mccxiv** [comment]
I might add it to user panels - So you'd have to first click on the broadcaster's name (or anyone else) in the viewer list first. I don't want to clutter the main UI
