### ISSUE TITLE
ability to add channel from command line

### ISSUE THREAD

**Issue by dreamfliper** [mccxiv/tc#264]
I want to make livestreamer-twich-gui to automatically launch tc as a chat client. livestreamer-twitch-gui allows custom chat client to open and pass through parameters via cli, such as channel name.

**Comment by mccxiv** [comment]
I like the idea but the logic is a little complex when the application is already open and you want to join a new channel. Tc doesn't allow multiple instances to launch.

I might work on this after a couple other small things I'm doing

**Comment by mccxiv** [comment]
I'm closing this because I don't see it happening anytime soon. 

If I can come up with an idea I'll revisit it. :smile:
