### ISSUE TITLE
Missing Description for Broadcaster

### ISSUE THREAD

**Issue by Zelakto** [mccxiv/tc#265]
[This](https://github.com/mccxiv/tc/blob/e0270e27f475d9d1c9af4505fc12d55663e67844/src/tc-renderer/ng/elements/chat-output/chat-output.js#L101) doesn't include a description for broadcaster, just thought I'd let you know. :D

**Comment by mccxiv** [comment]
Nice catch, I'm upgrading the system to use [this api](https://badges.twitch.tv/v1/badges/global/display?language=en) so it'll work with future badges too
