### ISSUE TITLE
Option for tiger striping in chat

### ISSUE THREAD

**Issue by jnki** [mccxiv/tc#273]
Is it planned for tiger striping in chat? It can make the chat more readable.

[Here's my bad mockup](http://i.imgur.com/y9f8LUT.png)

Thanks!

**Comment by mccxiv** [comment]
I like it. Maybe :+1:

**Comment by mccxiv** [comment]
Grouping up the same username was not trivial, even BTTV doesn't do it. 

But I managed!

![](http://puu.sh/qRLS7/d5bc5e119c.png)

Need to fix a couple small issues and make it line up on the left, then I'll push an update.

**Comment by mccxiv** [comment]
Out soon.
