### ISSUE TITLE
Couple of Feature Requests :)

### ISSUE THREAD

**Issue by XSilverlink** [mccxiv/tc#275]
First off love the application :) Love the overall style and whatnot! Feels very modern!

Well here they come!

- Clear Chat. (When i reopen my stream / chat i don't have to see the messages of the stream before)
- Pressing Closes really closes chat. (Maybe give it an option within the option menu or give a message: Do you want to close or minimize and with a tick Save option or something)
-  Show available emoticons in a menu or something

**Comment by mccxiv** [comment]
Hi, sorry for the slow response. 

1. I will consider it, but probably not soon.
2. Yes, adding an option would be good.
3. Definitely planned!

**Comment by mccxiv** [comment]
Thanks for the feedback, I'm closing this to clean up the issues list.  
Task number 3 is tracked by issue #8
