### ISSUE TITLE
Twitch Usernames Ending in Space Tab Completion Incorrect

### ISSUE THREAD

**Issue by bap14** [mccxiv/tc#276]
In a chat room, if a twitch user's username ends in a space (for whatever reason) Tc incorrectly displays the trailing space as "<username>\s" instead of a blank whitespace.

A user in SyntaxSe7en's chat, Legendary_Lisa, has her name end in a space (according to Twitch).  When using tab-completion, her name is completed to "Legendary_Lisa\s".  I opened up the twitch web chat just to be sure I could confirm this bug exists.

## Example chat experience from Twitch:
**kirttimukha9** : Pi sons you like it
_Moderator Subscriber Turbo_ **Legendary_Lisa**  : see you later @Buckalewbanzai
_Subscriber_ **Toxify__** : Finally back damn telephone  syn7WUT

## HTML from Twitch Web Chat
**Normal Username Examples:** 
`<span class="from" style="color:#5F9EA0" data-ember-action="3561">xkittyxoutlawx</span>`
`<span class="from" style="color:#008000" data-ember-action="3569">kirttimukha9</span>`
`<span class="from" style="color:#000000" data-ember-action="3585">Toxify__</span>`

**Trailing Space Username:**
`<span class="from" style="color:#00CCCC" data-ember-action="3578">Legendary_Lisa </span>`

## Expected result:
Legendary&lt;tab> ===> "Legendary_Lisa "

## Actual Result:
Legendary&lt;tab> ===> "Legendary_Lisa\s"

## Steps to reproduce:
1. Log in to SyntaxSe7en chat
2. Type "Legendary_" and then hit the tab key
3. Watch the auto-completion complete her name as: Legendary_Lisa\s

## System Info:
Windows 10 Pro x64
Tc 1.3.10

**Comment by mccxiv** [comment]
Thanks for the report! I've seen that issue with `\s` crop up in some other places. I'll add more parsing logic to deal with it.
