### ISSUE TITLE
Better support for emojis

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#278]
Let's not depend on the OS for emojis anymore. Do it like Twitter/Discord/Bttv.

**Comment by mccxiv** [comment]
Chrome 53 added support for emojis on Windows.

Electron 1.4.0 uses chrome 53 https://github.com/electron/electron/releases/tag/v1.4.0

I need to test if they actually work inside Electron - if they do, that'll be huge.

**Comment by mccxiv** [comment]
Yep, great news.

![](http://puu.sh/rue47/bd880c02c1.png)

However, I need to upgrade Electron all the way from `0.37.3` which is not trivial. I already tried once and gave up.

**Comment by kumpelblase2** [comment]
![butts](http://cdn.iwastesomuchtime.com/11212012002192.gif)
