### ISSUE TITLE
BTTV Pro Personal emotes not showing up.

### ISSUE THREAD

**Issue by jnki** [mccxiv/tc#287]
BTTV has a service which allows people to use their own personal emotes in other peoples channel.

> BetterTTV Pro grants you up to 25 channel emotes, 25 shared emotes, priority emote approval, **and allows up to 5 channel and shared non-GIF personal emotes to be used globally by you**

These emotes are not showing up in TC client

**Comment by mccxiv** [comment]
Hey, thanks for filing an issue. I've know about this limitation but I haven't found a BTTV API to get this info. 

I'll do some more investigating, maybe asking on the r/twitch Discord

**Comment by mccxiv** [comment]
Bttv guy confirmed that's not possible :( 

Hopefully in the future they'll change it

https://twitter.com/BetterTTV/status/795448476737814528
