### ISSUE TITLE
Twitch Badges Not Showing (v. 4.0.0)

### ISSUE THREAD

**Issue by Outsanity** [mccxiv/tc#302]
I'm going to assume it may have to do with the new Twitch API but only Twitch badges are not showing. All emotes seem to still show

**Comment by mccxiv** [comment]
Yeah I started noticing that today, getting this strange error

![](http://puu.sh/sAWXH/cfd4f9d587.png)

It's not even an API issue, just a regular image request failing. I'll investigate after work
