### ISSUE TITLE
Use Streamlink instead of Livestreamer

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#308]
Or both, if possible. Livestreamer is unmaintained.  
Streamlink: https://github.com/streamlink/streamlink

Suggestion from https://twitter.com/RonTTV/status/805348724012630016

**Comment by scsddeputy** [comment]
streamlink is a fork of livestreamer so the functionality should mostly be the same

**Comment by mccxiv** [comment]
Logic would be to check if Streamlink is installed, then fall back to checking if Livestreamer is installed

Hoping their API is identical.

**Comment by mccxiv** [comment]
I've made a PR https://github.com/mccxiv/tc/pull/321

However there's still an issue on Mac. For some reason it's not detecting the presence of livestreamer

When I try this in the REPL, using the same which module, it works as expected
```
> which('livestreamer', (e) => console.log(!e))
undefined
> true
```

**Comment by mccxiv** [comment]
@kumpelblase2 do you think it's something to do with the user that's running electron being in a different environment?

**Comment by kumpelblase2** [comment]
Might be different $PATH in your shell than for "normal" applications
