### ISSUE TITLE
Bit Cheermotes

### ISSUE THREAD

**Issue by scsddeputy** [mccxiv/tc#317]
Twitch's new bits cheermotes dont render in tc

**Comment by mccxiv** [comment]
Oh interesting, I missed that announcement.  

This would be high priority, we should have at least feature parity with twitch chat. I still have work tomorrow so I'll probably look into it at night or on sunday

**Comment by scsddeputy** [comment]
ill see if i can get it working and make a PR, no promises, got a full day of work tomorrow too

**Comment by scsddeputy** [comment]
There is an endpoint in the twitch api V5 to get the new cheermote/original cheer badges. To actually access the endpoint you will need to specify the Accept header with application/vnd.twitchtv.v5+json

Endpoint: https://api.twitch.tv/kraken/bits/actions

**Comment by mccxiv** [comment]
Yeah I'll fix this before the next release. Top priority especially now that all streamers have bits

**Comment by mccxiv** [comment]
Fixed in next release , including support for custom cheermotes. Also cheers now have a golden background 

![](https://puu.sh/xQBje/c084905dd3.png)
