### ISSUE TITLE
Failing to get badges

### ISSUE THREAD

**Issue by scsddeputy** [mccxiv/tc#326]
Been having problems with this for a few days now, it doesnt seem to be a constant issue, but seems to be happening more and more often as of late. Getting it when on windows, but not getting it when on linux.

![](http://i.imgur.com/scPAvVc.png)

**Comment by mccxiv** [comment]
Are you still able to reproduce? I'm not sure what could cause ERR_INSECURE_RESPONSE

**Comment by scsddeputy** [comment]
Yeah still having the issue. I'm not sure exactly what is causing it. I'll do some debugging this weekend and see what I come up with

**Comment by scsddeputy** [comment]
It seems that it is an issue with the brighttray being outdated and chromium is not accepting the certificates. Seems the only fix is to update the electron version

**Comment by mccxiv** [comment]
This used to be a problem, but that's what I did (updated electron) a while back to fix it. So I'm surprised that it still happened for you. Haven't seen anyone else report this though

**Comment by scsddeputy** [comment]
Im not sure, maybe it was an issue with my OS at the time, i have recently reset my os and now im not getting the issue anymore... ill mark as closed.
