### ISSUE TITLE
Add confirmation when unbanning someone

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#327]
```
13:21  nailcliper: one is that I'd like confirmation when unbanning someone FeelsBirthdayMan
```

 (which twitch event is that?)

**Comment by scsddeputy** [comment]
my guess would be the unban command https://docs.tmijs.org/v1.1.2/Commands.html#unban, i guess you could have a pop up that just asks if you really want to unban a person and then submit the command upon a yes response

**Comment by mccxiv** [comment]
Oh no, @nailcliper just meant a confirmation that the unbanning went through. Not an "are you sure?"

**Comment by scsddeputy** [comment]
oohhh, ok. My bad :P

**Comment by scsddeputy** [comment]
it would be a notice event, with the event of `unban_success` https://docs.tmijs.org/v1.1.2/Events.html#notice

**Comment by mccxiv** [comment]
So this isn't implemented and yet... 

![](https://puu.sh/wAxmn/700b8806f9.png)

Did twitch change something? :thinking:
