### ISSUE TITLE
Fix app closing logic

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#331]
Here's the desired behavior:

Windows:  
Close window -> hides window
Close from tray -> quits app
Click to update -> call `autoUpdater.quitAndInstall`

Mac:  
Close window -> hides window (But I think there's a mac-specific way, `app.hide`. Is that even necessary?)
Close from tray -> quits app
Click to update -> call `autoUpdater.quitAndInstall` (currently doesn't quit the app properly, either find a fix or workaround by calling `app.exit.bind(app, 0) after that call`

Linux:  
Close window -> quits app

---

Relevant files:  

- [`main.js`](https://github.com/mccxiv/tc/blob/master/src/tc-main/main.js) where the actual quitting happens
- [`tray-icon.js`](https://github.com/mccxiv/tc/blob/master/src/tc-renderer/lib/startup/tray-icon.js) tray quit event
- [`side-toolbar.js`](https://github.com/mccxiv/tc/blob/master/src/tc-renderer/ng/elements/side-toolbar/side-toolbar.js#L47) where quitAndInstall is called after an update

**Comment by mccxiv** [comment]
Tackling this should also fix https://github.com/mccxiv/tc/issues/324

**Comment by mccxiv** [comment]
@scsddeputy do you have time to try this? Otherwise I can

**Comment by scsddeputy** [comment]
So the windows logic all works right? Mac has the updating issue and Linux just needs the logic to quit on close. Is that all correct?

**Comment by mccxiv** [comment]
Yep, that's right. Though I would like to use the least amount of conditionals. So if a technique works for all, then I'd prefer it

**Comment by scsddeputy** [comment]
I can do the Linux fix while on lunch tonight.
