### ISSUE TITLE
Disable browser shortcuts when writing in chat

### ISSUE THREAD

**Issue by TzarAlkex** [mccxiv/tc#348]
I saw when using CTRL+SHIFT+arrow keys to select words while writing a chat message that it also changed tabs.
This is unexpected and confusing.

**Comment by TzarAlkex** [comment]
Also, is the shortcuts documented anywhere? I Assume this isn't the only one (but it's the only one I stumbled upon).

**Comment by mccxiv** [comment]
:( I keep finding conflicts with the shortcuts hah. We should rebind to something else but I'm not sure what

**Comment by mccxiv** [comment]
all right, 2 action items here

- Document shortcuts inside of the app, probably inside the settings menu
- Either rebind to something else, or disable keybinds when typing

**Comment by mccxiv** [comment]
Removed the offending keybind in the next version
