### ISSUE TITLE
(New Feature) Button for sharing via social media (specifically twitter)

### ISSUE THREAD

**Issue by Maxx57** [mccxiv/tc#361]
Hi, I love the ability to open the twitch channel I'm viewing, but when I'm viewing my own and playing a game, I want a simple way to tweet the link to my live game on twitter with my current twitter title. Is this something you'd consider adding? I know it's simple to just open the twitch channel and press the share button, but that takes away from my focus on the game I'm playing. Thanks for the consideration, kudos to all you've does so far!  I know I can pull the code and make the change myself, but figured you'd be up to the task.

**Comment by mccxiv** [comment]
Thanks for the idea, at the moment this kind of feature is outside the scope of the project

Tc has gotten some good adoption among streamers, which I'm grateful for - but at the core it's still meant to be just a chat client and not a streaming dashboard, I think there are better specialized tools out there for that

That said PRs are welcome 💃
