### ISSUE TITLE
Specify streamers who are live at the moment

### ISSUE THREAD

**Issue by lorensgwine** [mccxiv/tc#370]
My suggestions:
1. By using color of nickname;
2. By adding red (live) or gray (vodcast) circle next to nickname;
3. By moving tabs with live to the beginning;
4. 1+3 or 2+3.

**Comment by mccxiv** [comment]
I like the red/gray dot idea. 

And I also like 4, but I suspect it might be too disruptive for the general public to start moving their tabs around.

I'll start with 3 only for now, then I want to implement the ability to re-order tabs: #126

**Comment by kumpelblase2** [comment]
I would find it a little annoying if it moved my tabs around, maybe make that an option? Having a dot (similar to when chrome records your mic) sounds like a great idea.

**Comment by lorensgwine** [comment]
Option or button for moving tabs will be fine too
