### ISSUE TITLE
Stuck in a connection loop.

### ISSUE THREAD

**Issue by MadHalaster** [mccxiv/tc#373]
The chat portion will never connect to the sever for me. The thumbnail works fine, but chat when I first start says "Connecting...", then immediately after it says "Disconnected from server." followed by "Connecting..." over and over again. It is never successful.

Connecting to the same channel on the same PC with Chatty is working fine. Even side by side.

![tc issue](https://user-images.githubusercontent.com/15384106/33755059-fab6546e-dba3-11e7-8bd9-444a0a98b9bc.png)

This is with the latest version 10.3.0.

OS is Windows 10 patched to the latest version, so Creators Update.

**Comment by scsddeputy** [comment]
Open dev tools and provide a screenshot. To open make sure tc window is selected and press f12

**Comment by mccxiv** [comment]
This happens when the token becomes invalid for whatever reason, logging out and generating a new password will fix it. 

I thought I fixed the error handling (it should boot users to the login screen) but I guess something's wrong still

**Comment by MadHalaster** [comment]
Yep, that addressed the issue mccxiv. :) Logging out, generating a new password, and logging in.
Attaching a dev console screenshot anyways, though it probably wont help, since it looks like you already know what the issue is anyways.

Would like to note that the dev console is still displaying an error message in a loop, even after I have connected and everything appears to be working fine. Once a minute it displays:

error: Could not connect to server. Reconnecting in 30 seconds..   logger.js:11

![devconsole](https://user-images.githubusercontent.com/15384106/33802600-9b895972-dd2f-11e7-8688-72568bd6ba19.png)

**Comment by mccxiv** [comment]
Interesting, maybe this is the source of the mysterious memory leak. I'll look into the reconnection code

**Comment by scsddeputy** [comment]
looks like it might be an issue with the tmi.js library

**Comment by b1n4ryj4n** [comment]
same issue with the connection loop and check for updates failed because "502 Bad Gateway"
![connecting](https://user-images.githubusercontent.com/3122325/36050498-01a0e9fe-0de7-11e8-9c9e-56d198f03936.png)

**Comment by mccxiv** [comment]
Thanks for the report. I'm almost done moving house so I can get back to fixing these hiccups next week
