### ISSUE TITLE
Use https for the website

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#374]
Github pages doesn't support SSL for custom domains, but we can put cloudflare in front: https://hackernoon.com/set-up-ssl-on-github-pages-with-custom-domains-for-free-a576bdf51bc

> this setup is not fully secure — the connection between CloudFlare and GitHub pages is not secured

But better than nothing

**Comment by Saturate** [comment]
If you need help, just mention me. It's super easy to setup :-)

**Comment by mccxiv** [comment]
It actually works already https://gettc.xyz/

But it doesn't redirect from http -> https yet. Haven't looked into how to do that with github pages. Hopefully I don't need to resort to in page javascript

**Comment by scsddeputy** [comment]
You can do it via your dns manager

**Comment by Saturate** [comment]
If you use cloudflare just enable it there, they have both HSTS and HTTP A
redirect :-)
-- 


*Allan Kimmer Jensen*
+45 31 14 16 69 <javascript:void(0);>
allankimmerjensen@gmail.com
akj@pentia.dk
https://akj.io

**Comment by mccxiv** [comment]
Thanks all! It was indeed just a button on Cloudflare. 

Need to fix some resources (google fonts) to use the https version and then there won't be any warnings

**Comment by mccxiv** [comment]
Done
