### ISSUE TITLE
Windows 10 Store version

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#400]
Ok so this probably won't be very popular, but the ultimate goal is to leverage third party update mechanisms instead of trying to maintain my own. Some of the shittiest bugs I've had (and still having) have nothing to do with the code in this repository but are a result of the installer/updater. 

Goal:

- Mac app store
- Windows 10 store

as well as standalone executables (not installers). 

For linux, someone (not me) can feel free to maintain the release on their package manager of choice.

---

- [ ] Make an appx that gets accepted by the Win store
- [ ] Make sure auto-start feature works. [See this](https://blogs.windows.com/buildingapps/2017/08/01/configure-app-start-log/)
- [ ] Pay Apple $99 (ugh)
- [ ] Make a Mac App Store version

**Comment by scsddeputy** [comment]
i can put the linux package up on the snap store if thats okay with you

**Comment by mccxiv** [comment]
Having second thoughts on this plan. The reasons are non-technical and somewhat personal. Will halt this project for now and continue using the built in auto updater
