### ISSUE TITLE
Hotkey tooltips don't show ctrl

### ISSUE THREAD

**Issue by Bauke** [mccxiv/tc#404]
![Ctrl + S](https://user-images.githubusercontent.com/19501722/38991505-4d58f508-43de-11e8-891d-fc827976c2bf.png) ![Ctrl + N](https://user-images.githubusercontent.com/19501722/38991515-52e27cc4-43de-11e8-99e2-4428fc8d1e9d.png)

OS: Ubuntu 16.04
~~Not sure if it's OS specific, I'll try this on Windows 10 later and edit this issue.~~

![Ctrl + S](https://user-images.githubusercontent.com/19501722/38993639-7af061f8-43e4-11e8-8e2a-835ee147de90.png) ![Ctrl + N](https://user-images.githubusercontent.com/19501722/38993640-7b139de4-43e4-11e8-98b6-ab670af819e9.png)

OS: Windows 10

Edit: I don't have a Mac so can't test it on there, if anyone does feel free to post the results.

**Comment by Bauke** [comment]
After #403 where `return {restrict: 'E', template, link}` was changed to `return {restrict: 'E', scope: {}, template, link}` this seems to be fixed for the chat tabs (ctrl + n), I guess this is the problem for other tooltips too.

**Comment by mccxiv** [comment]
Yes, I think the scope bug you fixed in that PR also fixed this. I need to go through all directives and give them a local scope, or better yet convert them to `.component()` (angular 1.5+)
