### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by Bauke** [mccxiv/tc#407]
What are your thoughts on improving the build process? ie: making it so Mac will only build when on Mac, Linux won't build on Windows... Right now when running `npm run build` on Linux with Wine/Mono installed it'll always error with Mac. Which seems unnecessary as we can just use `process.platform` to check.

Something like this
```js
switch (process.platform) {
  case 'darwin':
    buildMac()
    buildLinux() // ? don't know if these 2 can build on Mac
    buildWindows() // ? 
    break
  case 'win32':
    buildWindows()
    break
  case 'linux':
    buildLinux()
    buildWindows()
    break
}
```

I don't know how the build process works on Mac so maybe we can't build Windows on there or something.

**Comment by mccxiv** [comment]
Yeah what happens right now is we attempt everything... which will only work on a mac. I don't mind changing it though so that there are less errors being thrown around
