### ISSUE TITLE
Emotes are missing from messages with unicode emojis

### ISSUE THREAD

**Issue by Iwasawafag** [mccxiv/tc#411]
Let's say we received such chat message (only relevant parts shown):

```json
{
  "message": "test message 😂😂 rooCry rooHappy rooVV",
  "userstate": {
    "emotes": {
        "904829": [ "16-21" ],
        "904848": [ "23-30" ],
        "904882": [ "32-36" ]
    }
  }
}
```

In this case Tc will embed no emotes in the message. Actual twitch chat handles it correctly. 

Haven't looked at the code, but I think it has something to do with code points - backend treats them as 1 character and thus those emote positions cannot be fed to `String.prototype.substring` as is. 

Considering it chooses to not include any emotes at all rather than display message incorectly and that there are no error messages in console my only guess is that it's intentional. Have you thought about using, say, [unicode-substring](yarn.pm/unicode-substring) module for this?

**Comment by mccxiv** [comment]
The switch to `twitch-js` must have re-broke it. I'll investigate
