### ISSUE TITLE
Double click selecting the oauth token adds a space to the front

### ISSUE THREAD

**Issue by Bauke** [mccxiv/tc#415]
![Selected oauth:token](https://user-images.githubusercontent.com/19501722/40880809-02b3e1be-66b8-11e8-9734-a855a0ebc98e.png)
When you double click to copy the oauth token it adds a space to ~~the front~~ both the front and the back (probably from some whitespace in the html or something) and makes the token appear invalid when pasting it into Tc

**Comment by mccxiv** [comment]
Aha, so this is why people are still complaining about endless disconnects. 

- [] fix site
- [] trim whitespace on both sides inside Tc when submitting login info
