### ISSUE TITLE
Legacy Private Chat Autocomplete not working and no User Symbols

### ISSUE THREAD

**Issue by Eloquenz** [mccxiv/tc#417]
Hello,

I and a bunch of other people are still in a Legacy Private Chat Room, which is only accessible through IRC or your client. 
The name of the room is in the following format: **_USERNAME_123456789**. Joining is possible without a problem, however inside the room Autocomplete for Emotes is not working and instead of the prime, turbo or mod symbol, there is just a blank space (Attached is a picture as an example, I should have a crown next to my name because I am a Prime User)
![ebwancx](https://user-images.githubusercontent.com/10514800/40889755-82fbbb76-676c-11e8-851f-d2bb047fac35.png)

I know that these Legacy Private Chat Rooms are not supported anymore, but maybe there is a quick fix to it because it would be nice if we could keep this room alive through your software.
.
Thanks.

**Comment by FlamingFox911** [comment]
It could be the API takes a while to load. Keep the window open for an hour or two and see if the badges load, then wait another hour or two to see if autocomplete works. Autocomplete will work if you can see the Viewer list.

**Comment by Eloquenz** [comment]
I had the Chat open for 24h already, no viewer list appeared and still no Autocomplete. Seems like a weird problem. Maybe the API won't accept the old chat rooms anymore.

**Comment by Eloquenz** [comment]
Okay, like I said, I had the chat room open for several hours, but no user list, no badges and still no autocomplete. We had a user in our group that fixed the icons in the v12 version, we had to exchange the **app.asar** file, but I don't know how he got that to work. I still have the **app.asar** file - maybe I should upload it? I am not sure if you are able to reverse engineer it though.

**Comment by mccxiv** [comment]
The Rooms feature is dead I think 🙈 

If someone is interested again please reopen
