### ISSUE TITLE
No viewer list in 15.2.0 on Mac 10.14

### ISSUE THREAD

**Issue by celina** [mccxiv/tc#478]
The viewer list has disappeared from my left column in 15.2.0 on Mac 10.14. I've logged out, left and rejoined channels, and attempted to downgrade to 15.1.0 to no change.

**Comment by mccxiv** [comment]
Sorry for the slow reply, if you're still around could you double check if you can unhide the viewer list by moving your mouse to the top-right side of the empty viewer list? There's a button there but there's a bug now where the icon is invisible: https://github.com/mccxiv/tc/issues/479

**Comment by celina** [comment]
That was it! Thank you- it was really rough using Chatty for the last week.
