### ISSUE TITLE
Subscription events no longer show months subscribed

### ISSUE THREAD

**Issue by timbeaudet** [mccxiv/tc#488]
Twitch may have changed the API but the display now shows "0 months in a row" even when the user has been subbed for many months. This is on Tc v15.3.0 for Windows.

![subscribed_bug](https://user-images.githubusercontent.com/1384686/52913256-466dfe00-328a-11e9-84cb-f321c43cc0ee.jpg)

**Comment by kajsa** [comment]
Also on 15.4.0 on Mint (using Ubuntu .deb)

**Comment by mccxiv** [comment]
Fixed a while ago (forgot to close this sorry)
