### ISSUE TITLE
Twitch is changing from v3 to v5 of their API

### ISSUE THREAD

**Issue by lemings68** [mccxiv/tc#494]
Twitch just swapped from V3 to V5 of their API, resulting in a lot of queries returning with 410 and the error "Gone" with various easter egg messages. The instantly visible result of this is that the badges from chat have disappeared.  
Any plans to migrate?
https://dev.twitch.tv/docs/v5/guides/migration/#v3-to-v5-migration-guide

**Comment by mccxiv** [comment]
Yuuuup! I plan to fix this within the next 24 hours

**Comment by mccxiv** [comment]
We did it
