### ISSUE TITLE
Need help with highlighting usernames

### ISSUE THREAD

**Issue by CreeperChief** [mccxiv/tc#497]
How do I write the username that I want to be highlighted?

Creeper:Chief or CreeperChief:Something?

**Comment by mccxiv** [comment]
This is how mine looks

![](http://puu.sh/E99b2/7871244f65.png)

Your own username is already automatically highlighted, but you can add variants.

The `user:` one means all the messages coming FROM that user will be highlighted regardless of what they say

**Comment by CreeperChief** [comment]
Oh okay, thanks.
