### ISSUE TITLE
the color is wrong for some chatters

### ISSUE THREAD

**Issue by mccxiv** [mccxiv/tc#50]

**Comment by mccxiv** [comment]
It's not wrong, gray color means they haven't picked one on Twitch. 

On twitch they'd get a random color every time they load chat

**Comment by kumpelblase2** [comment]
how about giving them a random color too? Or is there no way to distinguish between actually choosing grey and not having chosen a color at all?

**Comment by mccxiv** [comment]
I don't want to contribute to the confusion, maybe we can make default color poop brown? :hankey:

**Comment by kumpelblase2** [comment]
poop color best color :hankey: :+1:
