### ISSUE TITLE
No appimage for latest versions

### ISSUE THREAD

**Issue by urbels** [mccxiv/tc#512]
Hello! Why so? There will be no appimage versions anymore?

**Comment by mccxiv** [comment]
Heya, so my build machine broke because of OS X Catalina. But I believe appimage should be buildable on Windows so I'll try

**Comment by urbels** [comment]
That would be great! Thank you!

**Comment by amatol** [comment]
Hi! Any news?

**Comment by hexathos** [comment]
If you tell what you need, i could provide a jenkins instance on debian/buster :D

**Comment by mccxiv** [comment]
AppImage should once again be available going forward (added to the automated release process)
