### ISSUE TITLE
Digital Signature

### ISSUE THREAD

**Issue by DesertDog1178** [mccxiv/tc#516]
Why does TC not have a valid digital signature?
I get a notification that TC does not have a valid digital signature and that it wants to send information to static-cdn.jtvnw.net (151.101.198.214:443)

**Comment by mccxiv** [comment]
Hey, is this warning from some other software, do you have a screenshot? Tc uses `static-cdn.jtvnw.net` to get the twitch emotes

**Comment by DesertDog1178** [comment]
It randomly sorts through a list of 6 websites, but here is what pops up.
[https://i.imgur.com/lY2fk84.jpg](https://i.imgur.com/lY2fk84.jpg)

**Comment by mccxiv** [comment]
Closing as it's working as expected, outgoing calls are made to twitch APIs and Tc's website (update checking)
