### ISSUE TITLE
Bitdefender classifies Tc.exe as malware

### ISSUE THREAD

**Issue by av8rgeek** [mccxiv/tc#517]
When I downloaded Tc last night and tried to run it, Bitdefender classified it as malware, even though I got it from your website (https://github.com/mccxiv/tc/releases/download/15.7.0/tc-setup-win-15.7.0.exe).  The infection detected is Atc4.Detection.  The specific file locations were:

%APPDATA%\Local\Tc\Tc.exe
%APPDATA%\Local\Tc\app-15.7.0\Tc.exe
%HOMEPATH%\OneDrive\Desktop\Tc.lnk    << The desktop shortcut

Since the source is posted for anyone, I highly suspect this is a false positive.  It might be a good idea to double-check the code and submit your files to Bitdefender for analysis and reclassification.  https://www.bitdefender.com/submit/

Bitdefender Total Security 2020
Build 24.0.14.86
Threat Engine Version 7.83720
Last Engine Update:  2/5/2020 6:02 PM

Thanks for making a cool program!

**Comment by mccxiv** [comment]
Thanks for the report, as of now, Bitdefender seems ok with it: https://www.virustotal.com/gui/url/145044dd239bb6aafda8933978babd41d1a3ecee689cf1c4afdaed07fe09c83c/detection
